### ISSUE TITLE
Solutions page

### ISSUE THREAD

**Issue by erensunerr** [utmgdsc/UML_Mentor#19]
Page to enter solution for a particular challenge.

Possible design similar to leetcode is to have challenge details page on the left of the screen and solutions page on the right half of screen.

**Comment by Vladmidir** [comment]
I suggest against splitting the page in 2. 

My vision is that the work will be done in the editor in the separate tab and the submission would be a separate tab also. 

Again, this is similar to the FrontendMentor design below

![image](https://github.com/utmgdsc/UML_Mentor/assets/121591697/456c0a1c-48e2-4a7f-9a90-60dc87b56947)
![image](https://github.com/utmgdsc/UML_Mentor/assets/121591697/a753c631-3c08-4f38-a8d4-3a612ca3ec4d)
![image](https://github.com/utmgdsc/UML_Mentor/assets/121591697/9909f5e4-b7f6-4a1f-91b3-c06d50764a82)
